### ISSUE TITLE
CoM not working

### ISSUE THREAD

**Issue by linuxgurugamer** [DefiantZombie/FlightMarkers#7]
The CoM marker is not being recalculated as fuel is burned.  
Try launching KerbalX ( the rocket) and turn them on.  It only changes when parts are staged

**Comment by DefiantZombie** [comment]
Center of Mass marker is not being calculated by the mod. It is read directly from the vessel in KSP.

I am unable to attempt to replicate without knowing which KSP and mod version the bug is being reported for.

(I swear I wasn't ignoring you, Github appears to be refusing to send me notifications again)

**Comment by linuxgurugamer** [comment]
and I'm not ignoring you, either :-)
It would have been 1.8.1, and the current version of the mod

**Comment by DefiantZombie** [comment]
Unable to reproduce during my KSP 1.10.0 update checks. Closing issue.
